version: '3'
services:
  redis:
    container_name: redis-container
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password